version: 2.1

commands:
  destroy_environments:
    steps:
      - run:
        name: Destroy environment
        command: |
          aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID}
  fallar:
    docker:
      - image: 
    steps:
      - run:
        name: error simulado
        command: |
          return 1
      - destroy_environments:
        when: on_fail
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - fallar